apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: harbor
  labels:
    name: test-pod
spec:
  containers:
  - name: test-pod
    image: 10.1.0.1:30003/library/alpine:3.16.2
    command: ["/bin/sh", "-c"]
    args:
      - "sleep 5m"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
