imagePullSecrets:
  - name: test-web-robot

backend:
  init:
    image:
      repository: alpine
      tag: "3.16.2"
  container:
    image:
      repository: harbor.example.domain.com/test-web/test-backend
      tag: "dev"
    port: 80
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi
  updateStrategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate

frontend:
  container:
    image:
      repository: harbor.example.domain.com/test-web/test-frontend
      tag: "dev"
    port: 80
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi
  updateStrategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate

service:
  backend:
    type: ClusterIP
    port: 80
    # nodePort: 30081
  frontend:
    type: ClusterIP
    port: 80
    # nodePort: 30080

ingress:
  enabled: true
  labels:
    environment: production
    method: traefik
  hosts:
    - host: test-web.example.domain.com
      paths:
        - path: /
          pathType: Prefix

persistence:
  backend:
    enabled: true
    existingClaim: ""
    resourcePolicy: keep
    storageClass: "nfs-client"
    accessMode: ReadWriteMany
    size: 1Gi
    subPath: ""
